---
FJARRKONTROLLEN_GUB_OAUTH2_CLIENT_ID: baa1b536-9b65-403d-be1a-10eae7d13248
FORMS_GUB_OAUTH2_CLIENT_ID: 484546ce-0fb8-450d-b198-f5d70e715816
KOHA_SVC_URL: https://koha-staging-intra.ub.gu.se/cgi-bin/koha/svc
KOHA_SEARCH_URL: https://koha-staging-intra.ub.gu.se/cgi-bin/koha/catalogue/search.pl?q=
BIBLIOTEKSKORT_SERVICE_URL: https://bibliotekskort-staging.ub.gu.se
