---
FJARRKONTROLLEN_GUB_OAUTH2_CLIENT_ID: f40c897a-4ce2-4a4e-9c6f-7390332e5a3b
FORMS_GUB_OAUTH2_CLIENT_ID: 169fc014-148b-42d8-bee9-88cda1f454ff
KOHA_SVC_URL: https://koha-lab-intra.ub.gu.se/cgi-bin/koha/svc
KOHA_SEARCH_URL: https://koha-lab-intra.ub.gu.se/cgi-bin/koha/catalogue/search.pl?q=
BIBLIOTEKSKORT_SERVICE_URL: https://bibliotekskort-lab.ub.gu.se
